# Weights 
n_weights: 28 # Number of weight parameters
q_lin_v: 0.0008      # Cost for linear velocity control action
q_lin_acc: 0.03    # Cost for linear acceleration 
q_lin_ret: 0.05    # Cost for linear retardation 
q_lin_jerk: 0.0 # Cost for linear jerk
q_ang: 0.000001      # Cost angular velocity control action
q_ang_acc: 0.04    # Cost angular acceleration
q_ang_jerk: 0.0 # Cost for angular jerk
q_cte: 0.1         # Cost for cross-track-error from each line segment
q_pos_master: 0                # Cost for position deviation (each time step vs reference point)
q_pos_slave: 0               # Cost for position deviation (each time step vs reference point)
q_d_lin_vel_upper:  3             # Cost for upper speed deviation each time step
q_d_lin_vel_lower:  5             # Cost for lower speed deviation each time step
q_reverse: 0                 # Cost for reverse
q_d_ang_vel:  0               # Cost for speed deviation each time step
q_theta_master: 0             # Cost for each heading relative to the final refernce position
q_theta_slave: 0             # Cost for each heading relative to the final refernce position
q_pos_N: 0                # Terminal cost; error relative to final reference position         
q_theta_N: 0            # Terminal cost; error relative to final reference heading 
q_distance: 0 #0.00 # Cost for deviating from d
q_theta_diff: 0 # Cost for angular difference between robots
q_distance_c: 0 # Cost for deviating from d + tolerance, soft constraint
q_obs_c: 3000 # Cost for being inside an object, soft constraint
q_dyn_obs_c: 200 # Cost for being inside an dynamic object, soft constraint
q_future_dyn_obs: 0 #20 # Cost for being inside a future dyn obs
q_acc_c: 0 # Cost for acceleration, soft constraint
enable_distance_constraint: 0 #
q_formation_ang: 0 # cost for deviating from checkpoint
q_line_theta: 0.82 # Cost for deviating of the reference angle which is based on the lines



